name: CI - Micapipe Test

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  run-micapipe:
    runs-on: self-hosted
    timeout-minutes: 1440

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Micapipe Docker image
        run: docker build -t micapipe:test .

      - name: Build Singularity (.sif)
        run: |
          export SINGULARITY_TMPDIR=/export02/local/singularity_tmp
          singularity build --force /export02/local/singularity_tmp/micapipe_v0.2.3.sif docker-daemon://micapipe:test

      - name: Point test script at new .sif
        run: |
          sed -i "s|^container_img=.*|container_img=/export02/local/singularity_tmp/micapipe_v0.2.3.sif|" tests/sample_test.sh

      - name: Run Micapipe Test
        run: |
          chmod +x ./tests/sample_test.sh
          ./tests/sample_test.sh
